name: CI

on:
  push:
    branches:
      - main
    tags:
      - '**'
  pull_request:
  
jobs:

  tests:
    name: test coverage

    strategy:
      matrix:
        include:
          - python-version: "3.11"
            os: ubuntu-latest

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash -l {0}
        
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: refs/heads/${{ github.head_ref }}
      - name: create and activate env
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: mutis
          environment-file: environment.yml
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: install mutis
        run: |
          pip install -e .
      - name: test coverage
        run: |
          make test-cov
          codecov -X gcov

  docs:
    name: docs building

    strategy:
      matrix:
        include:
          - python-version: "3.11"
            os: ubuntu-latest

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: refs/heads/${{ github.head_ref }}
      - name: create and activate env
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: mutis
          environment-file: environment.yml
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: install mutis
        run: |
          pip install -e .
      - name: build docs
        run: |
          make docs-sphinx
